version: '3'

services:
  persist_gems:
    build:
      context: ../
      dockerfile: docker/gems.docker
    volumes:
      - gems:/gems

  db:
    build:
      context: ../
      dockerfile: docker/db.docker
    volumes:
      - ../src/tmp/db:/var/lib/postgresql/data
    depends_on:
      - persist_gems

  web:
    build:
      context: ../
      dockerfile: docker/web.docker
    command: ./start.sh
    volumes:
      - ../src:/tshpc
      - gems:/gems
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  gems:
